version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./dist/web:/app
    ports:
      - 8090:443
    restart: unless-stopped

  rasa-actions:
    image: kopernick/ciri-core:latest
    command: run actions
    env_file: .env
    restart: unless-stopped

  rasa-api:
    image: kopernick/ciri-core:latest
    command: run --enable-api --cors '*'
    env_file: .env
    restart: unless-stopped
