@startuml flow
|Frontend|
start
split
:listen for speech;
:transform speech to text;
split again
:capture text from input field;
end split
:add text to user message history
and display it in convesation window;
:send text to backend;

|Backend|
:detect intent;
:process action;
:compose intent response text
and send it to the user;

|Frontend|
:handle response;
:add text to assistant message history
and display it in convesation window;
:transform response text to speech and play it;


stop

@enduml
